Update to ALPHA7
SalmonGER/StatsPE pull request #66
Opened 2017-08-01 01:56 UTC by Aericio

#### **What does the PR do?**

Update to ALPHA7

#### **Why should this PR be merged?**

Updates plugin to work in ALPHA7

#### **Are the changes in this PR tested**?

- [ ] Yes
- [x] No

#### **Extra Information**

there might be more than just that, so i am creating a pr (unnecessary help salmon doesn't need, prob.)

2017-08-01 01:57 UTC, Aericio commented on src/SalmonDE/StatsPE/EventListener.php
> +            Base::getInstance()->getDataProvider()->saveData($event->getPlayer()->getName(), Base::getInstance()->getDataProvider()->getEntry('ClientID'), (string) $event->getPlayer()->getClientId())
as phpstorm says*

2017-08-02 12:48 UTC, SalmonDE commented on src/SalmonDE/StatsPE/EventListener.php
> +            Base::getInstance()->getDataProvider()->saveData($event->getPlayer()->getName(), Base::getInstance()->getDataProvider()->getEntry('ClientID'), (string) $event->getPlayer()->getClientId())
Why is the comment needed there?

2017-08-02 13:00 UTC, SalmonDE requested changes
Works, but the added comment in this pr should be removed.
Other than that, ready to merge.

2017-08-04 03:25 UTC, Aericio commented
understood.

2017-08-04 03:27 UTC, merged